# Generated by Django 4.1.7 on 2023-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('door_time', models.DateTimeField()),
                ('event_time', models.DateTimeField()),
                ('age_restriction', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('event_link', models.URLField()),
                ('stage', models.CharField(max_length=100)),
                ('sold_out', models.BooleanField(default=False)),
                ('thumbnail_image', models.URLField()),
                ('pinned', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
